### ISSUE TITLE
Have you tried to use @ViewScoped ManagedBeans?

### ISSUE THREAD

**Issue by rodrik** [bilak/spring-boot-primefaces-template#1]
I'm struggling to make them work in embedded tomcat/jetty.

**Comment by bilak** [comment]
Hi, yes I'm using viewscope but, I'm using it by spring. You can find implementation [here](http://blog.primefaces.org/?p=702). Add it to your application configuration and then just use @Scope("view"). If you are trying to use my application, there is issue with jsf-api/impl version. I have here version 2.2.11 and this version has removed classpath scanning for annotations. So just download to version 2.2.10 and it will work for you. You can then start this application with mvn clean spring-boot:run and access application on [http://localhost:8080/view/fileupload.xhtml](http://localhost:8080/view/fileupload.xhtml)

**Comment by rodrik** [comment]
Ok, that worked for me. Thanks!
